sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - wget https://nodejs.org/download/release/v8.8.1/node-v8.8.1-linux-x64.tar.gz
  - export REPO=$TRAVIS_REPO_SLUG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TAG .
  - docker images
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO

