sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - git ls-remote --tags https://chromium.googlesource.com/chromium/src.git > ./TAGS
  - cat ./TAGS | grep refs | cut -d/ -f3 | sort -rn | head -1 > ./VERSION
  - export LATEST_VERSION=`cat ./VERSION`
  - echo $LATEST_VERSION
  - export VERSION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo $LATEST_VERSION; else echo $TRAVIS_BRANCH ; fi`
  - echo $VERSION
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $TAG
  - export REPO=microbox/chrome-headless
  - echo $REPO
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

script:
  - docker build -t busybox-build --build-arg CHROMIUM_VERSION=${VERSION} busybox-build
  - export CID=$(docker create busybox-build)
  - docker cp $CID:/rootfs.tar busybox
  - docker rm $CID
  - docker build -t ${REPO}:${TAG}-slim busybox

after_success:
  - docker images
  - docker push $REPO

