sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - docker build -t busybox-build busybox-build
  - export CID=$(docker create busybox-build)
  - docker cp $CID:/rootfs.tar busybox
  - docker rm $CID

after_success:
  - export REPO=$TRAVIS_REPO_SLUG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TAG busybox
  - docker images
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO

